### ISSUE TITLE
Lighthouse shouldn't use "Learn more" links in its report

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/lighthouse#12241]
#### Provide the steps to reproduce

When running the SEO report in Lighthouse, it will flag uses of "Learn more" links as problematic. Ironically, the Lighthouse report itself uses "Learn more" links:

#### What is the current behavior?

The following screenshot is taken from the [Link Text](https://web.dev/link-text/) audit article on web.dev:

![159564551_130438489000377_2939511278204770703_n](https://user-images.githubusercontent.com/326742/111011151-667b2900-834d-11eb-9ee4-4591b3830b93.png)

#### What is the expected behavior?

We shouldn't be breaking our own recommendations 🙃

**Comment by connorjclark** [comment]
Please see our reasoning here: https://github.com/GoogleChrome/lighthouse/issues/5349

in short: this advice is for SEO, and Lighthouse reports aren't meant to be indexed.

**Comment by robdodson** [comment]
@connorjclark what about doing something like this:

```html
<div>Learn more <span class="visually-hidden">about [some audit name]</span></div>
```

that would satisfy screen reader users

**Comment by robdodson** [comment]
I think the real intent of this audit is for folks using screen readers so the reasoning in #5349, while understandable, doesn't cover the whole story.

It's covered a bit in [this article](https://web.dev/labels-and-text-alternatives/#links) but the tl;dr is when folks navigating with a screen reader are trying to find relevant links on the page they get something like this:

![image](https://user-images.githubusercontent.com/1066253/111014093-11441500-8357-11eb-8971-56e55b7c0e08.png)

A `.visually-hidden` class could look like this:

```css
// In order to let screen readers read content we want to hide, pulled from:
// https://css-tricks.com/small-tweaks-can-make-huge-impact-websites-accessibility/#article-header-id-2
.w-visually-hidden {
  clip: rect(1px 1px 1px 1px);
  clip: rect(1px, 1px, 1px, 1px);
  clip-path: inset(1px);
  display: block;
  height: 1px;
  overflow: hidden;
  position: absolute;
  white-space: nowrap;
  width: 1px;
}
```
