### ISSUE TITLE
Lighthouse (or chrome?) does not work on same docker image on different hosts

### ISSUE THREAD

**Issue by uuf6429** [GoogleChrome/lighthouse#14488]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://google.com

### What happened?

I set up lighthouse in a docker image (`thecodingmachine/php:8.1-v4-cli-node16`). It works on my machine, but it fails in bitbucket (using the same image). Here's the setup:
```shell
docker run -ti thecodingmachine/php:8.1-v4-cli-node16 bash

sudo apt-get update
sudo apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libxkbcommon0 libasound2 libcairo2 libpango-1.0-0

npm install chromium lighthouse

export CHROME_PATH=$(node -e 'process.stdout.write(require("chromium").path)')

node_modules/.bin/lighthouse https://google.com/ --output=json --quiet --chrome-flags='--headless --disable-gpu --no-sandbox --disable-dev-shm-usage --no-first-run' --form-factor=desktop --screenEmulation.mobile=false --no-enable-error-reporting --verbose
```

In the resulting log (see below) there is nothing from Chrome.

### What did you expect?

I expected at least some error message in the logs.
In the beginning I had a _similar_ behaviour when running locally because I was missing some libraries, but this was clearly mentioned in the logs - so I don't know why the logs are empty in bitbucket.

### How were you running Lighthouse?

node

### Lighthouse Version

9.6.8

### Chrome Version

Chromium 109.0.5396.0

### Node Version

v16.18.0

### OS

Ubuntu 20.04.5 LTS

### Relevant log output

```shell
Tue, 01 Nov 2022 21:29:56 GMT LH:ChromeLauncher:verbose created /tmp/lighthouse.6FOIZ8v
Tue, 01 Nov 2022 21:29:56 GMT LH:ChromeLauncher:verbose Launching with command:
"/opt/atlassian/pipelines/agent/build/vendor/node_modules/chromium/lib/chromium/chrome-linux/chrome" --disable-features=Translate --disable-extensions --disable-component-extensions-with-background-pages --disable-background-networking --disable-component-update --disable-client-side-phishing-detection --disable-sync --metrics-recording-only --disable-default-apps --mute-audio --no-default-browser-check --no-first-run --disable-backgrounding-occluded-windows --disable-renderer-backgrounding --disable-background-timer-throttling --disable-ipc-flooding-protection --password-store=basic --use-mock-keychain --force-fieldtrials=*BackgroundTracing/default/ --remote-debugging-port=43043 --disable-setuid-sandbox --user-data-dir=/tmp/lighthouse.6FOIZ8v --headless --disable-gpu --no-sandbox about:blank
Tue, 01 Nov 2022 21:29:56 GMT LH:ChromeLauncher:verbose Chrome running with pid 4519 on port 43043.
Tue, 01 Nov 2022 21:29:56 GMT LH:ChromeLauncher Waiting for browser.
Tue, 01 Nov 2022 21:29:56 GMT LH:ChromeLauncher Waiting for browser...
<snip>
Tue, 01 Nov 2022 21:30:21 GMT LH:ChromeLauncher Waiting for browser.......................................................................................................
Tue, 01 Nov 2022 21:30:21 GMT LH:ChromeLauncher:error connect ECONNREFUSED 127.0.0.1:43043
Tue, 01 Nov 2022 21:30:21 GMT LH:ChromeLauncher:error Logging contents of /tmp/lighthouse.6FOIZ8v/chrome-err.log
Tue, 01 Nov 2022 21:30:21 GMT LH:ChromeLauncher:error 
Unable to connect to Chrome
```

**Comment by uuf6429** [comment]
I created and ran the following pipeline and it succeeded, so I guess there must be something wrong in my current usage:
```yaml
image: thecodingmachine/php:8.1-v4-cli-node16
pipelines:
  custom:
    lighthouse:
      - variables:
          - name: SITE_URL
            default: https://google.com
      - step:
          name: lighthouse
          deployment: staging
          script:
            - sudo apt-get update
            - sudo apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libxkbcommon0 libasound2 libcairo2 libpango-1.0-0
            - npm install chromium lighthouse
            - export CHROME_PATH=$(node -e 'process.stdout.write(require("chromium").path)')
            - node_modules/.bin/lighthouse $SITE_URL --output=json --quiet --chrome-flags='--headless --disable-gpu --no-sandbox --disable-dev-shm-usage --no-first-run' --form-factor=desktop --screenEmulation.mobile=false --no-enable-error-reporting --verbose
```
