### ISSUE TITLE
Import jsons directly instead of reading file

### ISSUE THREAD

**Issue by doteric** [GoogleChrome/lighthouse#14951]
So I'm curious why are you using directory paths and reading files instead of directly importing JSONs using `import`?  
https://github.com/GoogleChrome/lighthouse/blob/main/shared/localization/locales.js#L31
I'm not sure on why is this approach taken, but I guess there is a reason?  

So for example an updated version could look like this:
```
import arLocale from './locales/ar.json';
...
```
And let the bundler (rollup here? in my case esbuild) handle this correctly.

The current method causes `esbuild` to not package the JSONs together with the bundle and results in errors.
```
ENOENT: no such file or directory, open '/var/task/locales/ar.json'
```

And also any suggested workaround for this?

**Comment by doteric** [comment]
So my preferred workaround approach was to split my code from the dependencies by create an AWS Lambda Layer. I've automated this by creating a `package.json` like so:  
```json
{
  "dependencies": {
    "@sparticuz/chromium": "^112.0.2",
    "lighthouse": "^10.1.0"
  }
}
```

And ten via CI:
```yaml
  script:
    - cd lambda_layer
    - yarn install --production=true
  artifacts:
    paths:
      - lambda_layer/node_modules/
    expire_in: 60 mins
```

And the rest is terraform code to create the zip, upload it to s3 and use it for the new lambda layer 😁 
Just writing it here if somebody stumbles upon the same problem in the fututre.
