### ISSUE TITLE
total-byte-weight started failing but only on the CLI

### ISSUE THREAD

**Issue by nstringham** [GoogleChrome/lighthouse#15717]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://othello-rust.web.app/

### What happened?

recently the `lhci autorun` command began giving the following error
```
       ✘  total-byte-weight failure for minScore assertion
       Avoids enormous network payloads
       https://developer.chrome.com/docs/lighthouse/performance/total-byte-weight/

        expected: >=0.9
           found: 0
      all values: 0, 0, 0
```

config:
```yaml
ci:
  collect:
    autodiscover-url-blocklist: /privacy-policy.html
  upload:
    target: "temporary-public-storage"
  assert:
    preset: "lighthouse:recommended"
    assertions:
      csp-xss: "off"
      bf-cache: "warn"
```

### What did you expect?

I would expect the CLI to pass because I do not get an error about "Avoid enormous network payloads" anywhere else. including in the HTML report generated by the CLI

### What have you tried?

using the lighthouse inside of chrome and using the lighthouse inside of page speed insights

### How were you running Lighthouse?

CLI

### Lighthouse Version

0.13.0

### Chrome Version

120.0.6099.129

### Node Version

v18.12.1

### OS

Windows 11 23H2

### Relevant log output

```shell
https://github.com/nstringham/othello-web-app/actions/runs/7315817257/job/19929865498
```
