### ISSUE TITLE
No usable firstMeaningfulPaint when using custom fonts

### ISSUE THREAD

**Issue by Yonben** [GoogleChrome/lighthouse#3918]
Hi,
I was running audits on my app and used my own font.
When importing it "as usual", the audit returned me the `No usable firstMeaningfulPaint` with a Performance score of 5.

After investigating, I realized the audit works when the font-face ONLY returns the woff font. Any other format, even while working properly in the browser, will cause the error.

My `fonts.css` causing the error:
```css
@font-face {
    font-family: OmnesATT2-Regular;
    src: url('./fonts/omnesatt2-regular-webfont.eot');
    src: url('./fonts/omnesatt2-regular-webfont.eot?#iefix') format('embedded-opentype'),
    url('./fonts/omnesatt2-regular-webfont.ttf');
}
```

The working version:
```css
@font-face {
    font-family: OmnesATT2-Regular;
    src: url('./fonts/omnesatt2-regular-webfont.woff');
}
```
