### ISSUE TITLE
Using lighthouse in combination with travis

### ISSUE THREAD

**Issue by Simply007** [GoogleChrome/lighthouse#4931]
Hello,

How should I check whether the lighthouse score is 100 in travis?

My current travis config:
```
dist: trusty
language: node_js
node_js:
- "stable"
before_script:
- npm install
before_deploy:
- npm run build
deploy:
  provider: surge
  project: ./dist/
  domain: https://kentico-cloud-sample-pwa-app.surge.sh 
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^master|v3-angular$
after_deploy:
  - npm run lighthouse
```

My package.json scripts:
```
...
    "scripts": {
        "ng": "ng",
        "start": "ng serve",
        "build": "ng build --prod",
        "lint": "ng lint",
        "e2e": "ng e2e",
        "generate-models": "cd src/app/models && kc-generate --ts --projectId 66ab95de-6599-0018-f141-3c9dc08fe797 --definitions",
        "deploy-surge": "npm run build && surge ./dist https://kentico-cloud-sample-pwa-app.surge.sh",
        "lighthouse": "lighthouse --chrome-flags=\"--headless\" --quiet --output json https://kentico-cloud-sample-pwa-app.surge.sh"
    },
...
```

I am using surge for deployment (credentials are set in environment variable correcty).

I don't know, how to configure script lighthouse to fail if PWA score is less the 100.
