### ISSUE TITLE
Integrate proto linter

### ISSUE THREAD

**Issue by Hoten** [GoogleChrome/lighthouse#6376]
See https://github.com/GoogleChrome/lighthouse/pull/6374#issuecomment-432495947.

**Comment by exterkamp** [comment]
Yes please!  Make sure you find one that enforces proto linting rules + a max line width + indention checking!

**Comment by Hoten** [comment]
[prototool](https://github.com/uber/prototool)

```
prototool format -w lighthouse-result.proto
```

![image](https://user-images.githubusercontent.com/4071474/47798845-53201380-dce6-11e8-8da0-fd79fa821c6b.png)

I don't like how it removes newlines between fields. Don't see a way to disable that.

**Comment by yoheimuta** [comment]
> Make sure you find one that enforces proto linting rules + a max line width + indention checking!

I found this issue while making https://github.com/yoheimuta/protolint. This linter enforces proto linting official style guide, a max line length and a consistent indentation style.

I was interested about whether it could works for this project, I tried protolint under #6374 situation.

```
/y/C/lighthouse ❯❯❯ git diff
diff --git a/proto/lighthouse-result.proto b/proto/lighthouse-result.proto
index e4468277..14138da8 100644
--- a/proto/lighthouse-result.proto
+++ b/proto/lighthouse-result.proto
@@ -163,10 +163,10 @@ message LighthouseResult {

     // Corresponds to: https://www.w3.org/TR/performance-timeline-2/#idl-def-performanceentrylist
     repeated PerformanceEntry entries = 2;
-  }
+ }

-  // The performance timing data for the Lighthouse run
-  Timing timing = 14;
+ // The performance timing data for the Lighthouse run
+ Timing timing = 14;
 }

 // Message containing a category
/y/C/lighthouse ❯❯❯ ~/.go/bin/pl -fix .; echo $?
[proto/lighthouse-result.proto:166:2] Found an incorrect indentation style " ". "  " is correct.
[proto/lighthouse-result.proto:169:2] Found an incorrect indentation style " ". "  " is correct.
[proto/lighthouse-result.proto:168:2] Found an incorrect indentation style " ". "  " is correct.
1
/y/C/lighthouse ❯❯❯ git diff
/y/C/lighthouse ❯❯❯ ~/.go/bin/pl .; echo $?
0
/y/C/lighthouse ❯❯❯         
```

This project needs the config file named `.protolint.yaml`. The linter ignores a ENUM_FIELD_NAMES_UPPER_SNAKE_CASE rule because the file already violates it.

```yaml
# Lint directives.
lint:
  # Linter rules.
  # Run `pl list` to see all available rules.
  rules:
    # The specific linters to remove.
    remove:
      - ENUM_FIELD_NAMES_UPPER_SNAKE_CASE

  # Linter rules option.
  rules_option:
    # INDENT rule option.
    indent:
      # Available styles are 4(4-spaces), 2(2-spaces) or tab.
      style: 2
```

If it's fine, how about integrating the protolint?
