### ISSUE TITLE
Score gauge CSS on report is invalid

### ISSUE THREAD

**Issue by exterkamp** [GoogleChrome/lighthouse#6947]
Invalid trailing comma
```css
.lh-scores-header .lh-gauge__wrapper,
.lh-scores-header .lh-gauge--pwa__wrapper, {
  margin: 0 4px;
}
```
