### ISSUE TITLE
DBW: old css flexbox audit improvements

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/lighthouse#768]
- [ ] consider usage of vendor prefixes
- [ ] consider usage of other older properties from https://www.w3.org/TR/2009/WD-css3-flexbox-20090723/ (e.g. box-flex, box-orient, box-flex-group, display: flexbox (2011 version))

**Comment by graph1994** [comment]
Okay so the problem for this that I see is that we need to check for a number of propValues but the styles-helpers.js takes only strings atm for propValue param, possibly extend it to allow the checking for an array? Looks like .indexOf is being used for the check so it might be able to just handle an array?
Please let me know if I'm over thinking this! 
Example:
`const propValues = [ 'box-flex' , 'flexbox', 'box-orient', 'box-flex-group' ] `

**Comment by VanTanev** [comment]
This test will wrongly fail with multiple definitions in the form of
```css
.someClass {
    // 2009
    display: -webkit-box;
    display: -moz-box;
    display: box;

    // 2012
    display: -webkit-flex;
    display: -moz-flex;
    display: -ms-flexbox; // 2011 (IE 10)
    display: flex;
}
```

A browser will use the proper spec if available and not incur the penalty, but the above fails the audit because styles-gatherer will not overwrite multiple declarations of the same property.

cc @ebidel decided to write here instead of opening a new issue.
